"""Add hidden_subjects table

Revision ID: 02d315fd539f
Revises: bba5cb937cc5
Create Date: 2026-07-17 12:28:14.416663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d315fd539f'
down_revision: Union[str, Sequence[str], None] = 'bba5cb937cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('weekday', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tg_users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id', 'subject', 'weekday', name='uq_user_subject_weekday')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hidden_subjects')
    # ### end Alembic commands ###
