"""Add cascade delete for hidden_subjects

Revision ID: 29de7f1b70e2
Revises: 02d315fd539f
Create Date: 2026-07-17 14:02:51.326726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29de7f1b70e2'
down_revision: Union[str, Sequence[str], None] = '02d315fd539f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
