"""initial schema

Revision ID: 3e9c8838b6c3
Revises: 
Create Date: 2026-07-23 00:38:35.555225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9c8838b6c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_times',
    sa.Column('class_num', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('class_num')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=20), nullable=False),
    sa.Column('weekday', sa.String(length=20), nullable=False),
    sa.Column('class_num', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.String(length=255), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('lesson_type', sa.String(length=10), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vk_users',
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('notify_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_time', sa.Integer(), nullable=True),
    sa.Column('notify_before_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.vk_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_user_id', 'subject', name='uq_user_subject')
    )
    op.create_table('hidden_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('weekday', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.vk_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_user_id', 'subject', 'weekday', name='uq_user_subject_weekday')
    )
    op.create_table('homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('remind_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.vk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    op.drop_table('hidden_subjects')
    op.drop_table('filters')
    op.drop_table('vk_users')
    op.drop_table('schedule')
    op.drop_table('groups')
    op.drop_table('class_times')
    # ### end Alembic commands ###
