"""Change time fields to integer

Revision ID: 84cf07fbc8fd
Revises: 93e554555025
Create Date: 2026-07-16 13:11:02.215882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84cf07fbc8fd'
down_revision: Union[str, Sequence[str], None] = '93e554555025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE schedule ALTER COLUMN start_time TYPE INTEGER USING EXTRACT(EPOCH FROM start_time)::integer")
    op.drop_column('schedule', 'send_time')
    op.execute("ALTER TABLE tg_users ALTER COLUMN notify_time TYPE INTEGER USING EXTRACT(EPOCH FROM notify_time)::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_users', 'notify_time',
               existing_type=sa.Integer(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.add_column('schedule', sa.Column('send_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.alter_column('schedule', 'start_time',
               existing_type=sa.Integer(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
