"""fix schedule time fields

Revision ID: 95b5ab16629f
Revises: 93e554555025
Create Date: 2026-07-13 18:11:28.814627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95b5ab16629f'
down_revision: Union[str, Sequence[str], None] = '93e554555025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('pair_num', sa.Integer(), nullable=False))
    op.add_column('schedule', sa.Column('end_time', sa.Time(), nullable=False))
    op.drop_column('schedule', 'send_time')
    op.drop_column('schedule', 'class_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('class_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('send_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'end_time')
    op.drop_column('schedule', 'pair_num')
    # ### end Alembic commands ###
