"""Add description and remind_time fields to homeworks table

Revision ID: b8aefa4d137d
Revises: d188b1bc25b3
Create Date: 2026-07-19 00:18:05.248432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8aefa4d137d'
down_revision: Union[str, Sequence[str], None] = 'd188b1bc25b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('homeworks', sa.Column('remind_time', sa.Integer(), nullable=True))
    op.alter_column('homeworks', 'file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homeworks', 'file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('homeworks', 'remind_time')
    op.drop_column('homeworks', 'description')
    # ### end Alembic commands ###
