"""Add lesson_type field to schedule table

Revision ID: d188b1bc25b3
Revises: 29de7f1b70e2
Create Date: 2026-07-19 00:00:11.385250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd188b1bc25b3'
down_revision: Union[str, Sequence[str], None] = '29de7f1b70e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('lesson_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'lesson_type')
    # ### end Alembic commands ###
